// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrashTracker.Infrastructure.DAL.Context;

#nullable disable

namespace TrashTracker.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(TrashTrackerDbContext))]
    [Migration("20251016124705_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrashTracker.Domain.Date.CollectionDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LocalityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WasteTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocalityId");

                    b.HasIndex("WasteTypeId");

                    b.ToTable("CollectionDates");
                });

            modelBuilder.Entity("TrashTracker.Domain.Integrations.AlertzyIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertzyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserIdentityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AlertzyIntegrations");
                });

            modelBuilder.Entity("TrashTracker.Domain.Local.IntegrationLocality", b =>
                {
                    b.Property<Guid>("LocalityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertzyIntegrationId")
                        .HasColumnType("uuid");

                    b.HasKey("LocalityId", "AlertzyIntegrationId");

                    b.HasIndex("AlertzyIntegrationId");

                    b.ToTable("IntegrationLocalities");
                });

            modelBuilder.Entity("TrashTracker.Domain.Local.Locality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Localities");
                });

            modelBuilder.Entity("TrashTracker.Domain.Waste.WasteType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WasteTypes");
                });

            modelBuilder.Entity("TrashTracker.Domain.Date.CollectionDate", b =>
                {
                    b.HasOne("TrashTracker.Domain.Local.Locality", "Locality")
                        .WithMany("CollectionDates")
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashTracker.Domain.Waste.WasteType", "WasteType")
                        .WithMany("CollectionDates")
                        .HasForeignKey("WasteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locality");

                    b.Navigation("WasteType");
                });

            modelBuilder.Entity("TrashTracker.Domain.Local.IntegrationLocality", b =>
                {
                    b.HasOne("TrashTracker.Domain.Integrations.AlertzyIntegration", "AlertzyIntegration")
                        .WithMany("IntegrationLocalities")
                        .HasForeignKey("AlertzyIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashTracker.Domain.Local.Locality", "Locality")
                        .WithMany()
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertzyIntegration");

                    b.Navigation("Locality");
                });

            modelBuilder.Entity("TrashTracker.Domain.Integrations.AlertzyIntegration", b =>
                {
                    b.Navigation("IntegrationLocalities");
                });

            modelBuilder.Entity("TrashTracker.Domain.Local.Locality", b =>
                {
                    b.Navigation("CollectionDates");
                });

            modelBuilder.Entity("TrashTracker.Domain.Waste.WasteType", b =>
                {
                    b.Navigation("CollectionDates");
                });
#pragma warning restore 612, 618
        }
    }
}
