FROM node:lts-alpine as build
WORKDIR /app
COPY ./src/ClientApp/MyApp ./
RUN npm install
RUN npm install -g @angular/cli@latest
RUN ng test --watch=false --browsers=ChromeHeadless
RUN ng build 

FROM nginx:stable-alpine as production
COPY --from=build /app/dist/my-app/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]