<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\RequestClient\RequestClient\RequestClient.csproj" />
      <ProjectReference Include="..\..\Shared\Shared.Infrastructure\Shared.Infrastructure.csproj" />
      <ProjectReference Include="..\TrashTracker.Core\TrashTracker.Core.csproj" />
      <ProjectReference Include="..\TrashTracker.Domain\TrashTracker.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DAL\Migrations\" />
    </ItemGroup>

    <ItemGroup>
        <None Update="./TrainingData/pol.traineddata">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
        <None Update="./TrainingData/pol.traineddata">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
    </ItemGroup>

</Project>
