// <auto-generated />
using System;
using FeeTracker.Infrastructure.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FeeTracker.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(FeeTrackerDbContext))]
    partial class FeeTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeeTracker.Domain.Contributor.FeeContributor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FeeContributors");
                });

            modelBuilder.Entity("FeeTracker.Domain.Participant.FeeParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ContributorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeePurposeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.HasIndex("FeePurposeId");

                    b.ToTable("FeeParticipants");
                });

            modelBuilder.Entity("FeeTracker.Domain.Purpose.FeePurpose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("FeePurposes");
                });

            modelBuilder.Entity("FeeTracker.Domain.PurposeOwner.FeePurposeOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("FeePurposeOwners");
                });

            modelBuilder.Entity("FeeTracker.Domain.Participant.FeeParticipant", b =>
                {
                    b.HasOne("FeeTracker.Domain.Contributor.FeeContributor", "Contributor")
                        .WithMany("FeeParticipants")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeeTracker.Domain.Purpose.FeePurpose", "FeePurpose")
                        .WithMany("Participants")
                        .HasForeignKey("FeePurposeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");

                    b.Navigation("FeePurpose");
                });

            modelBuilder.Entity("FeeTracker.Domain.Purpose.FeePurpose", b =>
                {
                    b.HasOne("FeeTracker.Domain.PurposeOwner.FeePurposeOwner", "Owner")
                        .WithMany("FeePurposes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FeeTracker.Domain.Contributor.FeeContributor", b =>
                {
                    b.Navigation("FeeParticipants");
                });

            modelBuilder.Entity("FeeTracker.Domain.Purpose.FeePurpose", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("FeeTracker.Domain.PurposeOwner.FeePurposeOwner", b =>
                {
                    b.Navigation("FeePurposes");
                });
#pragma warning restore 612, 618
        }
    }
}
