name: Generate SSL Certificate

on:
  workflow_dispatch:  # Uruchamianie ręczne

jobs:
  generate-ssl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Certbot
        run: |
          sudo apt update
          sudo apt install -y certbot python3-certbot-nginx

      - name: Generate SSL Certificate
        run: |
          sudo certbot certonly --nginx -d myappzone.pl \
          --email test@test.pl --non-interactive --agree-tos

      - name: Copy Certificates to Artifacts Directory
        run: |
          mkdir -p ssl_certs
          sudo cp -r /etc/letsencrypt/live/myappzone.pl ssl_certs/

      - name: Upload SSL Certificate as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssl-certificate
          path: ssl_certs/
