name: publish

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  FRONTEND_PATH: Dockerfiles/Dockerfile.frontend
  BACKEND_PATH: Dockerfiles/Dockerfile.backend
  FRONTEND_IMAGE: myapp-frontend:latest
  BACKEND_IMAGE: myapp-backend:latest

jobs:
  convert-actor-username:
    name: Convert actor username
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Convert actor username to lowercase
        id: USER_NAME
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.actor }}
          format: lowercase

  build-and-publish-images:
    name: Build & Publish Images
    runs-on: ubuntu-latest

    needs: convert-actor-username

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        run: |
          echo ${{secrets.PAT}} | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: Build and Publish Frontend
        run: |
          docker build -f ${{env.FRONTEND_PATH}} . --tag ${{env.REGISTRY}}/${{needs.convert-actor-username.outputs.USER_NAME}}/${{env.FRONTEND_IMAGE}}
          docker push ${{env.REGISTRY}}/${{needs.convert-actor-username.outputs.USER_NAME}}/${{env.FRONTEND_IMAGE}}

      - name: Build and Publish Backend
        run: |
          docker build -f ${{env.BACKEND_PATH}} . --tag ${{env.REGISTRY}}/${{needs.convert-actor-username.outputs.USER_NAME}}/${{env.BACKEND_IMAGE}}
          docker push ${{env.REGISTRY}}/${{needs.convert-actor-username.outputs.USER_NAME}}/${{env.BACKEND_IMAGE}}


  deploy:
    needs: build-and-publish-images
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{secrets.SSH_HOST}} > ~/.ssh/known_hosts
    - name: connect and pull
      run : ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd ${{secrets.WORK_DIR}} && docker compose pull && docker compose up -d && exit"
    - name: cleanup
      run: rm -rf ~/.ssh