name: Publish Services

on:
  workflow_dispatch:
  push:
    branches:
      - microservices-microfrontends

env:
  REGISTRY: ghcr.io

jobs:
  initialize-environment:
    name: Initialize Environment
    runs-on: ubuntu-latest

    outputs:
      repo_name: ${{ steps.extract-name.outputs.REPO_NAME }} 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Repository Name
        id: extract-name
        uses: ./.github/actions/extract-repo-name

      - name: Login to Docker
        uses: ./.github/actions/login-to-docker
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  publish-services:
    name: Publish Services
    needs: initialize-environment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "identity"
            path: "./microservices/Identity/Identity.Api/Dockerfile"
          - name: "featureflags"
            path: "./microservices/FeatureFlags/FeatureFlags.Api/Dockerfile"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 
        
      - name: Build and Publish ${{ matrix.name }} Service
        uses: ./.github/actions/build-and-publish-docker
        with:
          dockerfile: ${{ matrix.path }}
          image_name: ${{ matrix.name }}
          registry: ${{ env.REGISTRY }}
          namespace: ${{ needs.initialize-environment.outputs.repo_name }}
        continue-on-error: true
