name: Publish Micro Frontends

on:
  workflow_dispatch:
  push:
    branches:
      - microservices-microfrontends
      - main

env:
  REGISTRY: ghcr.io

jobs:
  initialize-environment:
    name: Initialize Environment
    runs-on: ubuntu-latest

    outputs:
      repo_name: ${{ steps.extract-name.outputs.REPO_NAME }} 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Repository Name
        id: extract-name
        uses: ./.github/actions/extract-repo-name

  publish-services:
    name: Publish Micro Frontends
    needs: initialize-environment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "default-frontend"
            dockerPath: "./previous_frontend/MyApp/Dockerfile"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Login to Docker
        uses: ./.github/actions/login-to-docker
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Publish ${{ matrix.name }} Micro Frontend
        uses: ./.github/actions/build-and-publish-docker
        with:
          dockerfile: ${{ matrix.dockerPath }}
          image_name: ${{ matrix.name }}
          registry: ${{ env.REGISTRY }}
          namespace: ${{ needs.initialize-environment.outputs.repo_name }}
